apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-issuer"
spec:
  tls:
  - hosts:
    - mywisecow.duckdns.org # Change this to your DuckDNS subdomain
    secretName: wisecow-tls
  rules:
  - host: mywisecow.duckdns.org # Change this to your DuckDNS subdomain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wisecow-service
            port:
              number: 80
